name       : haskell-bifunctors
version    : 5.5.2
release    : 2
source     :
    - https://hackage.haskell.org/package/bifunctors-5.5.2/bifunctors-5.5.2.tar.gz : 332bb2ea19e77dac55282daff8046d89f69514ced5b987779d887e53b5d7cb11
license    : BSD-3-Clause
component  : programming.haskell
summary    : Bifunctors
description: |
    Bifunctors
builddeps  :
    - haskell-cabal-install
    - haskell-comonad
    - haskell-th-abstraction
    - haskell-transformers-compat
setup      : |
    sed -i "s|< 0.6|< 0.7|g" bifunctors.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
