name       : haskell-bifunctors
version    : 5.4.1
release    : 1
source     :
    - http://hackage.haskell.org/package/bifunctors-5.4.1/bifunctors-5.4.1.tar.gz : 3746f971f69ce31ced23d12e4785d96985f5c620ac7a26d5f4efead970c43b87
license    : BSD-3-Clause
component  : programming.haskell
summary    : Bifunctors
description: |
    Bifunctors
builddeps  :
    - haskell-cabal-install
    - haskell-comonad
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
