name       : haskell-bifunctors
version    : 5.5.7
release    : 4
source     :
    - https://hackage.haskell.org/package/bifunctors-5.5.7/bifunctors-5.5.7.tar.gz : 88b3a2d4504e1139a3aef7027913faa0870631477d0a2ebb6fa67d494cdb3532
license    : BSD-3-Clause
component  : programming.haskell
summary    : Bifunctors
description: |
    Bifunctors
builddeps  :
    - haskell-cabal-install
    - haskell-comonad-devel
    - haskell-th-abstraction-devel
rundeps    :
    - devel:
        - haskell-comonad-devel
        - haskell-th-abstraction-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
